<a href="https://colab.research.google.com/github/BilalKhaliqWillis/BILAL-Assignment2/blob/main/BILAL_Assignment_3_Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Assignment 3: Introduction to TensorFlow
# Importing TensorFlow
"""
Import TensorFlow library
"""
import tensorflow as tf

In [2]:
# Tensor Constants and Operations
"""
Creating constants and perform basic operations
"""

# Creating TensorFlow constants
a = tf.constant([5, 3, 8])
b = tf.constant([3, -1, 2])

# Sum using tf.add
sum_tf = tf.add(a, b)

# Sum using + operator
sum_plus = a + b

# Product using tf.multiply
product_tf = tf.multiply(a, b)

# Product using * operator
product_star = a * b

# Exponential operation - requires float type
a_float = tf.cast(a, tf.float32)
exp_a = tf.math.exp(a_float)

# Printing results
print("Sum using tf.add:", sum_tf)
print("Sum using + :", sum_plus)

print("\nProduct using tf.multiply:", product_tf)
print("Product using * :", product_star)

print("\nExponential of a:", exp_a)

Sum using tf.add: tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)
Sum using + : tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)

Product using tf.multiply: tf.Tensor([15 -3 16], shape=(3,), dtype=int32)
Product using * : tf.Tensor([15 -3 16], shape=(3,), dtype=int32)

Exponential of a: tf.Tensor([ 148.41316    20.085537 2980.958   ], shape=(3,), dtype=float32)


In [3]:
# TensorFlow Variables and Assignment
"""
Working with TensorFlow variables
"""

# Creating variable initialized to 0
current_state = tf.Variable(0)

# Creating constant with value 5
five = tf.constant(5)

# Adding current_state and five
new_value = current_state + five

# Assigning new_value to current_state
current_state.assign(new_value)

# Printing result
print("Updated current_state:", current_state.numpy())


Updated current_state: 5


In [4]:
# Creating Variables W and b
"""
Creating variables W and b
"""

# Variable W: shape (10, 10) filled with ones
W = tf.Variable(tf.ones((10, 10)))

# Variable b: shape (10, 1) filled with zeros
b = tf.Variable(tf.zeros((10, 1)))

print("W shape:", W.shape)
print("b shape:", b.shape)


W shape: (10, 10)
b shape: (10, 1)


In [5]:
# Creating W_dec
"""
Task 4:
Create W_dec with ten times the value of W
"""

W_dec = W * 10

print("W_dec:")
print(W_dec)

W_dec:
tf.Tensor(
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]], shape=(10, 10), dtype=float32)


In [6]:
# Tensor Reshaping
"""
Creating and reshaping a tensor
"""

# Original tensor
myTensor = tf.constant([[1, 2],
                         [3, 4],
                         [5, 6],
                         [7, 8]])

# Reshaping tensor from (4, 2) to (2, 4)
reshapedTensor = tf.reshape(myTensor, (2, 4))

# Printing tensors
print("Original Tensor (shape 4x2):")
print(myTensor)

print("\nReshaped Tensor (shape 2x4):")
print(reshapedTensor)

Original Tensor (shape 4x2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)

Reshaped Tensor (shape 2x4):
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
